#!/bin/bash
# migrate-to-keychain.sh — Move ~/.credentials/ secrets into macOS Keychain.
#
# After running:
#   • All secrets live encrypted in Keychain (login keychain, AES-256)
#   • Each .env file is replaced by a .env.sh loader that exports vars from Keychain
#   • google-client-secrets.json is stored as a single Keychain entry
#   • start-backend.sh is updated to source the loader before launching uvicorn
#   • Plaintext originals are zero-overwritten then deleted (backup kept until confirmed)
#
# To load credentials in any shell script afterwards:
#   source ~/.credentials/ai-orchestrator.env.sh
#
# To retrieve a single value:
#   security find-generic-password -a "$USER" -s ANTHROPIC_API_KEY -w

set -euo pipefail

# error-guard: shared try/catch + 10-failure circuit breaker (lib/error-guard.sh)
_eg_d="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
while [ "$_eg_d" != "/" ] && [ ! -f "$_eg_d/lib/error-guard.sh" ]; do _eg_d="$(dirname "$_eg_d")"; done
[ -f "$_eg_d/lib/error-guard.sh" ] && . "$_eg_d/lib/error-guard.sh"; unset _eg_d
command -v guard_run >/dev/null 2>&1 || guard_run() { shift; "$@"; }
command -v guard_throw >/dev/null 2>&1 || guard_throw() { printf 'error-guard: throw: %s\n' "$*" >&2; return 1; }

CREDS_DIR="${HOME}/.credentials"
ACCOUNT="$(whoami)"
BACKUP_DIR="${CREDS_DIR}.backup.$(date +%Y%m%d_%H%M%S)"

BACKEND_SCRIPT="${HOME}/Library/Application Support/ai-orchestrator/start-backend.sh"

pass=0; fail=0; skip=0

log()  { echo "         $*"; }
ok()   { echo "  [OK]   $*"; pass=$((pass + 1)); }
warn() { echo "  [WARN] $*"; skip=$((skip + 1)); }
err()  { echo "  [FAIL] $*"; fail=$((fail + 1)); }

# ── Store one key/value in Keychain ──────────────────────────────────────────
store_key() {
    local service="$1" value="$2"
    if [[ -z "$value" ]]; then
        warn "Skipped $service — empty value"
        return
    fi
    # -U: update silently if already exists
    if security add-generic-password -a "$ACCOUNT" -s "$service" -w "$value" -U 2>/dev/null; then
        ok "Stored  $service"
    else
        err "Failed  $service"
    fi
}

# ── Write one retrieval line to a loader script ───────────────────────────────
loader_line() {
    local loader="$1" key="$2"
    printf 'export %s=$(security find-generic-password -a "%s" -s "%s" -w 2>/dev/null || true)\n' \
        "$key" "$ACCOUNT" "$key" >> "$loader"
}

# ── Zero-overwrite then delete a file ────────────────────────────────────────
shred_file() {
    local f="$1"
    local size
    size=$(wc -c < "$f" 2>/dev/null || echo 0)
    if [[ "$size" -gt 0 ]]; then
        dd if=/dev/zero of="$f" bs=1 count="$size" 2>/dev/null || true
    fi
    rm -f "$f"
    ok "Shredded $(basename "$f")"
}

# ─────────────────────────────────────────────────────────────────────────────

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║        Keychain Credential Migration                     ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ── 1. Backup ─────────────────────────────────────────────────────────────────
echo "── 1. Backup ────────────────────────────────────────────────"
cp -R "$CREDS_DIR" "$BACKUP_DIR"
chmod -R 700 "$BACKUP_DIR"
ok "Backup → $BACKUP_DIR"
echo ""

# ── 2. Migrate .env files ─────────────────────────────────────────────────────
echo "── 2. Migrate .env files ────────────────────────────────────"
for envfile in "$CREDS_DIR"/*.env; do
    [[ -f "$envfile" ]] || continue
    name=$(basename "$envfile")
    echo ""
    log "Processing $name …"

    loader="${envfile%.env}.env.sh"
    {
        printf '#!/bin/bash\n'
        printf '# Keychain loader for %s\n' "$name"
        printf '# Source this file to export all credentials into the current shell:\n'
        printf '#   source %s\n' "$loader"
        printf '#\n'
        printf '# Generated by migrate-to-keychain.sh — do not add plaintext values here.\n\n'
    } > "$loader"
    chmod 700 "$loader"

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip blank lines and comments
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue

        # Parse KEY=VALUE — value may contain = signs (URLs, tokens)
        if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
            key="${BASH_REMATCH[1]}"
            value="${BASH_REMATCH[2]}"
            # Strip surrounding single or double quotes
            value="${value#\"}" ; value="${value%\"}"
            value="${value#\'}" ; value="${value%\'}"

            guard_run "store_key" store_key "$key" "$value" || true
            guard_run "loader_line" loader_line "$loader" "$key" || true
        fi
    done < "$envfile"

    ok "Loader  → $(basename "$loader")"
done

# ── 3. Migrate google-client-secrets.json ────────────────────────────────────
echo ""
echo "── 3. Migrate google-client-secrets.json ────────────────────"
JSON_FILE="$CREDS_DIR/google-client-secrets.json"
if [[ -f "$JSON_FILE" ]]; then
    json_content=$(< "$JSON_FILE")
    guard_run "store_key" store_key "google-client-secrets" "$json_content" || true

    # Loader that writes the JSON to stdout — pipe to a temp file when needed
    loader="${CREDS_DIR}/google-client-secrets.sh"
    {
        printf '#!/bin/bash\n'
        printf '# Retrieve google-client-secrets.json from Keychain.\n'
        printf '# Usage: source this file to set $GOOGLE_CLIENT_SECRETS_JSON,\n'
        printf '#        or write to a temp file:\n'
        printf '#          bash %s > /tmp/client_secrets.json\n' "$loader"
        printf '#\n'
        printf '# Generated by migrate-to-keychain.sh\n\n'
        printf 'GOOGLE_CLIENT_SECRETS_JSON=$(\n'
        printf '    security find-generic-password -a "%s" -s "google-client-secrets" -w 2>/dev/null || true\n' "$ACCOUNT"
        printf ')\n'
        printf 'export GOOGLE_CLIENT_SECRETS_JSON\n'
        printf '\n'
        printf '# If called directly (not sourced), print the JSON:\n'
        printf '[[ "${BASH_SOURCE[0]}" == "${0}" ]] && printf %%s "$GOOGLE_CLIENT_SECRETS_JSON"\n'
    } > "$loader"
    chmod 700 "$loader"
    ok "Loader  → $(basename "$loader")"
else
    warn "google-client-secrets.json not found — skipping"
fi

# ── 4. Update start-backend.sh ───────────────────────────────────────────────
echo ""
echo "── 4. Update start-backend.sh ───────────────────────────────"
if [[ -f "$BACKEND_SCRIPT" ]]; then
    if grep -q "ai-orchestrator.env.sh" "$BACKEND_SCRIPT" 2>/dev/null; then
        warn "start-backend.sh already sources loader — no change needed"
    else
        # Insert source line after the export PATH= line
        sed -i '' '/^export PATH=/a\
\
# Load credentials from macOS Keychain\
# shellcheck source=/dev/null\
source "${HOME}/.credentials/ai-orchestrator.env.sh"
' "$BACKEND_SCRIPT"
        ok "Updated start-backend.sh to source Keychain loader"
    fi
else
    warn "start-backend.sh not found at expected path — skip"
fi

# ── 5. Shred plaintext originals ─────────────────────────────────────────────
echo ""
echo "── 5. Shred plaintext originals ─────────────────────────────"
for envfile in "$CREDS_DIR"/*.env; do
    [[ -f "$envfile" ]] || continue
    guard_run "shred_file" shred_file "$envfile" || true
done
if [[ -f "$JSON_FILE" ]]; then
    guard_run "shred_file" shred_file "$JSON_FILE" || true
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
printf  "║  Done: %3d stored   %3d skipped   %3d failed            ║\n" $pass $skip $fail
echo    "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  Backup at: $BACKUP_DIR"
echo "  Once you've confirmed the app starts correctly, delete it:"
echo "    rm -rf \"$BACKUP_DIR\""
echo ""
echo "  To verify a value was stored:"
echo "    security find-generic-password -a $ACCOUNT -s ANTHROPIC_API_KEY -w"
echo ""
echo "  To load all ai-orchestrator vars in any shell session:"
echo "    source ~/.credentials/ai-orchestrator.env.sh"
echo ""

if [[ $fail -gt 0 ]]; then
    echo "  WARNING: $fail key(s) failed to store — check output above."
    exit 1
fi
